openapi: 3.1.0
info:
  title: Monitoring Endpoints
  description: New observability and monitoring endpoints for DevEx/QA/Security infrastructure
  version: 1.0.0

paths:
  /health:
    get:
      summary: Health Check with Error Budget
      description: Returns system health status including database connectivity, uptime, and remaining error budget
      tags:
        - Monitoring
      responses:
        '200':
          description: System is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [healthy, degraded, unhealthy]
                  timestamp:
                    type: string
                    format: date-time
                  uptime_seconds:
                    type: integer
                    description: System uptime in seconds
                  database:
                    type: object
                    properties:
                      connected:
                        type: boolean
                      latency_ms:
                        type: number
                  error_budget:
                    type: object
                    properties:
                      uptime_slo_target:
                        type: number
                        example: 0.999
                      current_uptime:
                        type: number
                        example: 0.9995
                      budget_consumed_pct:
                        type: number
                        example: 0
                      remaining_downtime_minutes:
                        type: number
                        example: 43.8
                      burn_rate:
                        type: number
                        example: 0.5
                required:
                  - status
                  - timestamp
                  - uptime_seconds
                  - database
                  - error_budget

  /metrics:
    get:
      summary: Prometheus Metrics
      description: Exposes application metrics in Prometheus text format
      tags:
        - Monitoring
      responses:
        '200':
          description: Metrics in Prometheus format
          content:
            text/plain:
              schema:
                type: string
                example: |
                  # HELP http_requests_total Total number of HTTP requests
                  # TYPE http_requests_total counter
                  http_requests_total{method="GET",endpoint="/api/v1/properties",status="200"} 1234

                  # HELP http_request_duration_seconds HTTP request latency
                  # TYPE http_request_duration_seconds histogram
                  http_request_duration_seconds_bucket{method="GET",endpoint="/api/v1/properties",le="0.1"} 980
                  http_request_duration_seconds_bucket{method="GET",endpoint="/api/v1/properties",le="0.5"} 1200

  /trace:
    get:
      summary: Request Tracing Demo
      description: Demonstrates request ID propagation across system components (debug endpoint)
      tags:
        - Monitoring
      responses:
        '200':
          description: Trace information
          content:
            application/json:
              schema:
                type: object
                properties:
                  request_id:
                    type: string
                    format: uuid
                    description: Unique request ID
                  trace_log:
                    type: array
                    items:
                      type: string
                    description: Log of trace points through system
                    example:
                      - "Middleware: Request received"
                      - "Endpoint: /trace handler invoked"
                      - "Database: Query executed"
                      - "Response: 200 OK"
                required:
                  - request_id
                  - trace_log
